### ISSUE TITLE
NdArray Objects example shape incorrect?

### ISSUE THREAD

**Issue by ThorodanBrom** [opengeospatial/CoverageJSON#186]
Hello,

In the CoverageJSON document section [NdArray Objects](https://github.com/opengeospatial/CoverageJSON/blob/master/standard/clause_specification_text.adoc#ndarray-objects), the shape of the example claims to be `[4, 2]`. 

https://github.com/opengeospatial/CoverageJSON/blob/0610e4f13977986806b4edc574b4f7eb6ea99c6b/standard/clause_specification_text.adoc?plain=1#L672

However, the rest of the examples indicate that this may be incorrect, and the correct shape should be `[2, 4]`. 

Apologies if this is a dud issue, it's just that my colleagues and I have been trying to understand the specification and this particular example always seems to trip us up. If anyone could provide any clarification for this, it would really help.

Thanks!

**Comment by jonblower** [comment]
Well spotted! Actually, the example JSON is still technically consistent, because the `values` array is one-dimensional and it has the correct number of entries. But the positions of the newlines are visually misleading. However, the paragraph below the example in the spec is simply wrong (my fault, as I think I wrote this!), and implies that the shape of the array is indeed `[2, 4]`.

I've made a pull request to correct this. Thanks for reporting!

**Comment by ThorodanBrom** [comment]
Thanks @jonblower, happy to help

**Comment by jonblower** [comment]
@chris-little I guess we can close this now the PR is merged, or should we wait until the corrected version is released?

**Comment by chris-little** [comment]
I've added a public release V1.0 tag, so will close.
